### ISSUE TITLE
Build PDF fails

### ISSUE THREAD

**Issue by wmat** [riscv/docs-dev-guide#15]
Build PDF action fails with:

Error: Error: The process '/opt/hostedtoolcache/Ruby/2.6.10/x64/bin/bundle' failed with exit code 5
    at ExecState._setResult (/home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:5340:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:5323:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:5217:27)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)

**Comment by wmat** [comment]
Fixed by adding libwebp-dev and libzstd-dev to the apt_packages.txt file in the dependencies folder.
